spring.application.name=wedding-invitation-jairo

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/wedding_invitation_jairo
spring.datasource.username=postgres
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080